# Catnip config
catnip:
# To play 18+ songs/videos you must log in to your verified adult account on your browser and select which one you use below.
# Supported options: BRAVE, CHROME, CHROMIUM, EDGE, FIREFOX, OPERA, SAFARI, VIVALDI, WHALE
# If you do not have this option select NONE
  cookiesFromBrowser: FIREFOX
  permission:
    deathCountManagement: VIP
#    Permission level: ALL -> SUB -> VIP -> MOD -> STREAMER
    music:
        request: ALL
        remove: MOD
        removeLastSelf: ALL
        voteSkip: ALL
        forceSkip: MOD
        blacklist: MOD
        userAction:
          blacklistUser: MOD

  cache:
    maximumSongDurationSeconds: 420
    directories: [
      "/cache/",
      "/cache/music/",
      "/cache/music/backup-playlist/",
      "/cache/music/download/",
    ]

# Springboot config
spring:
  application:
    name: Catnip
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

logging:
  level:
    #    root: TRACE
    #    org.springframework.web: TRACE
    dev.taway.catnip: TRACE
